# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-08 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_upload_name_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='pic',
            field=models.ImageField(upload_to=b'/home/minhdo/code/blog/media/images/', verbose_name=b'Image'),
        ),
    ]
