# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-12 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170812_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='pic',
            field=models.ImageField(upload_to=b'images/', verbose_name=b'Image'),
        ),
    ]
