# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-10 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170812_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='pic',
            field=models.ImageField(upload_to=b'images/'),
        ),
    ]
