# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-10 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170910_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='pic',
            field=models.ImageField(upload_to=b'images/', verbose_name=b'Image'),
        ),
    ]
