# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-17 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170910_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Acc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('age_date', models.DateTimeField(verbose_name=b'your age')),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='upload',
            name='name_pic',
        ),
    ]
