# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-18 11:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170917_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='name_pic',
            field=models.CharField(default=datetime.datetime(2017, 9, 18, 11, 56, 58, 360099, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
