# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-18 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_upload_name_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='name_pic',
        ),
    ]
